keys:
  - &nipe 4753AAAFB9CEA80BC71FD4BFB44ED4FEEA721B9E
creation_rules:
  - path_regex: nix/secrets/[^/]+\.(yaml|json)$
    key_groups:
    - pgp:
      - *nipe
    age: >-
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyFKf13fTsY2jO5SnO7NntMGzk7RXHVEXjQTwp9eLD6eixbDzWvo1O7Q4/mXh6vB0COhKEmylFRY6f3IjGtKmj8SuuiJJNgwx8TTsWGzCbXujJuXbXq/AgRRZFa+p3RGddSdo3yAW5Y2Eixdecu75spZ6DgqPgXheNSRIsY5sXRo5cYbKi+diWlFqgf11cjkXfW0xwaarxyfgPZZX876Auo79bM9t7qpJqMtywF6t5RU8sGY24/z1O6LRJTMRTsuSbFp/NS1AJJ+UMx+KM+fpMlxTra0TU0ei36t4F7NAqaOjbO4cIydEsOesNcaZCzgUWdyE2DRm0kxMqTDrnuz54PnhAB7M1L9iOdaGxF3ZsPpRSa0vpZCROyLloT4+FPaX7PFjOssG2vcg5fTCTNArE8zdcg1RhEmeONOQhf1KdJwWm/BVyBqtslZ/VSc7VJTHtLdBwZ/g+FfwWe1GyNQBrTOv33nupp4/d7R7rkB52QGKat1iAFKDsXfeX4JF1aVbLP6ENln7+flCePufkvficQXq9MPak1pnm1+4x9dpI78eXJ8FnQU0uoygBJ6NIeiXGx6OAy6Jdx7VLEKmwxkL6Y7vhsR9q09oc4WTE/XAiNDMZrD0/qlzvulWfyiohUdDslzNQdJiTEQgVcFBjY12PjuZnv3GID885HgKLiwNfBw==
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH1lAveTpTw/lV0FkBpbxttxfeaoWgfWC7TnADmwhVTf,
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMZPQuDCC7n1bXtV3vahNSxliOZPBbnUCf+7DqvQTanO
