name: Build

on: [push, pull_request]

jobs:
  update-nixpkgs:
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Setup Cachix
        uses: cachix/cachix-action@v11
        with:
          name: gowi
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build and switch to nix-darwin env
        run: |
          # Create /run directory
          echo -e "run\tprivate/var/run" | sudo tee -a /etc/synthetic.conf >/dev/null
          /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -t &>/dev/null || true
          # Prevent conflict between Cachix installed by workflow and the one installed in the config
          nix-env --set-flag priority 1 cachix
          # Build and switch to bootstrap config
          nix build .#darwinConfigurations.cicd.system
          # Build and switch to full config
          #/run/current-system/sw/bin/fish -c 'darwin-rebuild switch --flake .#githubCI'
          /run/current-system/sw/bin/darwin-rebuild switch --flake ".#cicd"
      
      # - name: Update flake.lock
      #   uses: DeterminateSystems/update-flake-lock@v13
      #   id: update_flakes
      #   with:
      #     pr-title: "Update flake.lock"
      #     pr-labels: dependencies
# test
